---
- name: Check URLs and Generate Status Page
  hosts: automation_controller
  gather_facts: no
  vars:
    urls:
      - "https://aap01.aroque.com.br"
      - "https://web01.aroque.com.br"
      - "https://web02.aroque.com.br"
    html_output: "/opt/local/html/index.html"

  tasks:
    - name: Check URLs status
      uri:
        url: "{{ item }}"
        method: GET
        return_content: false
      register: http_responses
      loop: "{{ urls }}"
      ignore_errors: true

    - name: Generate HTML content
      template:
        src: index.j2
        dest: "{{ html_output }}"
        mode: '0644'
      vars:
        urls: "{{ http_responses.results }}"

    - name: Print results to console (optional)
      debug:
        msg: "{{ item.item }} - {{ item.status }}"
      loop: "{{ http_responses.results }}"
