---
- name: Check URLs and Generate Status Page
  hosts: automation_controller
  gather_facts: no
  vars:
    urls:
      - "https://www.ansible.com/"
      - "https://access.redhat.com/"
      - "https://developers.redhat.com/"
    html_output: "/opt/local/html/index.html"

  tasks:
    - name: Check URLs status
      uri:
        url: "{{ item }}"
        method: GET
        return_content: false
      register: http_responses
      loop: "{{ urls }}"
      ignore_errors: true

    - name: Generate HTML content
      copy:
        dest: "{{ html_output }}"
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>System Status</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .header { background-color: lightgrey; padding: 10px 20px; }
                  h1 { color: #333; }
                  .url-list { margin-top: 20px; }
                  .url { padding: 10px; margin-bottom: 10px; color: white; }
                  .ok { background-color: darkgreen; }
                  .notok { background-color: darkred; }
              </style>
          </head>
          <body>
              <div class="header">
                  <h1>SYSTEM STATUS</h1>
              </div>
              <div class="url-list">
                  {% for response in http_responses.results %}
                  <div class="url {{ 'ok' if response.status == 200 else 'notok' }}">
                      {{ response.item }} - {{ 'OK' if response.status == 200 else 'NOTOK' }}
                  </div>
                  {% endfor %}
              </div>
          </body>
          </html>
        mode: '0644'

    - name: Print results to console (optional)
      debug:
        msg: "{{ item.item }} - {{ item.status }}"
      loop: "{{ http_responses.results }}"
